---
# tasks file for IIS_php
- name: Ensure Packages Folder exists
  win_dsc5:
    resource_name="file"
    Ensure="Present"
    Type="Directory"
    DestinationPath="{{ PackageFolder }}"
  tags:
    - Filesystem

- name: IIS-Prerequisites
  win_feature: name="Web-Server,Web-Mgmt-Tools,web-Default-Doc,Web-Dir-Browsing,Web-Http-Errors,Web-Static-Content,Web-Http-Logging,web-Stat-Compression,web-Filtering,web-CGI,web-ISAPI-Ext,web-ISAPI-Filter"
  tags:
    - WindowsFeature
    - PHP

- name: Visual C 2012 Thingy
  win_dsc5:
    resource_name="package"
    path="{{ Vc2012RedistDownloadUri }}"
    item_name="Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61030"
    Arguments="/install /passive /norestart"
    ProductId="{CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}"
  tags:
    - Install

- name: Make sure the PHP archive is in the package folder
  win_dsc5:
    resource_name="xRemoteFile"
    uri="{{ phpDownloadUri }}"
    DestinationPath="{{ PackageFolder }}\php.zip"
  tags:
    - Payload
    - Filesystem

- name: Make sure the content of the PHP archine are in the PHP path
  win_dsc5:
    resource_name="Archive"
    Path="{{ PackageFolder }}\php.zip"
    Destination="{{ phpPath }}"
  tags:
    - Payload
    - Filesystem

- name: Make sure the MySql extention for PHP is in the main PHP path
  win_dsc5:
    resource_name="File"
    SourcePath="C:\php\ext\php_mysql.dll"
    DestinationPath="C:\php\php_mysql.dll"
    MatchSource="true"
  tags:
    - Payload
    - Filesystem

- name: Make sure the php.ini is in the Php folder
  win_dsc5:
    resource_name="File"
    SourcePath="C:\Program Files\WindowsPowerShell\Modules\xPhp\Samples\PhpConfigTemplate.txt"
    DestinationPath="C:\php\php.ini"
    MatchSource="true"
  tags:
    - Config

- name: Make sure the php cgi module is registered with IIS
  win_dsc5:
    resource_name="xIisModule"
    item_name="phpFastCgi"
    Path="C:\php\php-cgi.exe"
    RequestPath="*.php"
    Verb="*"
    Ensure="Present"
  tags:
    - Config
    - IIS

- name: Make sure the php binary folder is in the path
  win_dsc5:
    resource_name="Environment"
    item_name="Path"
    value="C:\php"
    Ensure="Present"
    Path="true"
  tags:
    - Config
