---
# tasks file for Win_MySQL
- name: Make sure the mySqlServer installer package is present
  win_dsc5:
    resource_name="Package"
    Path="{{ mySqlInstallerUrl }}"
    ProductId="{{ mySqlInstallerProductId }}"
    item_name="MySQL Installer"

- name: Make sure the mySqlServer exists with the correct root credential
  win_dsc5:
    resource_name="xMySqlServer"
    ServiceName="MySqlService"
    Ensure="Present"
    RootPassword_username="mysqladmin"
    RootPassword_password="{{ mySqlAdminPassword }}"

- name: Make sure the MySql WordPress database exists
  win_dsc5:
    resource_name="xMySqlDatabase"
    Ensure="Present"
    item_name="{{ wordpress_db_name }}"
    ConnectionCredential_username="mysqladmin"
    ConnectionCredential_password="{{ mySqlAdminPassword }}"

- name: Make sure the MySql WordPress user exists
  win_dsc5:
    resource_name="xMySqlUser"
    item_name="wordpressuser"
    Ensure="present"
    ConnectionCredential_username="mysqladmin"
    ConnectionCredential_password="{{ mySqlAdminPassword }}"
    Credential_username="{{ wordpress_user_name }}"
    Credential_password="{{ wordpress_user_password}}"

- name: Make sure the MySql WordPress user has access to tho WordPress database
  win_dsc5:
    resource_name="xMySqlGrant"
    username="wordpressuser"
    DatabaseName="{{ wordpress_db_name }}"
    Ensure="present"
    ConnectionCredential_username="mysqladmin"
    ConnectionCredential_password="{{ mySqlAdminPassword }}"