---
# tasks file for Win_Wordpress
- name: Make sure the WordPress site folder is present
  win_dsc5:
    resource_name="file"
    Ensure="Present"
    Type="Directory"
    DestinationPath={{ WordPressPath }}
  tags:
    - Filesystem

- name: Remove default web site
  win_dsc5:
    resource_name="xWebSite"
    item_name="Default Web Site"
    Ensure="Absent"
    PhysicalPath="C:\inetput\wwwroot"

- name: Make sure the WordPress Iis site is present
  win_dsc5:
    resource_name="xWebSite"
    item_name="WordPress"
    Ensure="Present"
    State="Started"
    DefaultPage="index.php"
    ApplicationPool="DefaultAppPool"
    PhysicalPath={{ WordPressPath }}
  tags:
    - WordPress

- name: Make sure the WordPress archive is in the package folder
  win_dsc5:
    resource_name="xRemoteFile"
    Uri="http://WordPress.org/latest.zip"
    DestinationPath="{{ PackagesPath }}\wordpress.zip"
  tags:
    - WordPress

- name: Make sure wordpress file is in the root WP Directory
  win_dsc5:
    resource_name="xArchive"
    Path="{{ PackagesPath }}\wordpress.zip"
    Destination={{ WordPressPath }}
  tags:
    - WordPress